import { ProductState, ProductStatus } from './product.interface';

export const productInitialState: ProductState = {
  isFetching: false,
  myProduct: {
    isFetching: false,
    page: 0,
    totalPage: 1,
    data: [],
  },
  selectedProduct: null,
  form: {
    _id: null,
    name: '',
    nameError: null,
    description: '',
    descriptionError: null,
    full_description: '',
    full_descriptionError: null,
    sku: '',
    skuError: null,
    price: 0,
    priceError: null,
    is_limit_quantity: true,
    quantity: 0,
    quantityError: null,
    discount_percent: 0,
    discount_percentError: null,
    thumbnail: '',
    thumbnailError: null,
    images: [],
    imagesError: null,
    category: null,
    categoryError: null,
    status: ProductStatus.Active,
    international_shipping_fee: 0,
    international_shipping_feeError: null,
    national_shipping_fee: 0,
    national_shipping_feeError: null,
  },
  totalStatistic: [],
};
