export const routeName = {
  login: '/login',
  register: '/register',
  verifyAccount: '/verify-account',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  deposit: '/deposit',
  withdraw: '/withdraw',
  swap: '/swap',
  transfer: '/transfer',
  membershipFees: '/membership-fees',
  transferToExternal: '/transfer-to-external',
  network: '/network',
  wallet: '/wallet',
  lending: '/lending',
  invitationCode: '/invitation',
  changePassword: '/change-password',
  profile: '/profile',
  kyc: '/profile/kyc',
  scanQR: '/scan-qr',
  franchise: '/franchise',
  createToken: '/create-token',

  home: '/',
  products: '/products',
  productDetail: '/product-detail',
  cart: '/cart',
  chooseDeliveryAddress: '/choose-delivery-address',
  deliveryAddress: '/delivery-address',
  payment: '/payment',
  notification: '/notification',
  orders: '/orders',
  orderDetail: '/order-detail',
  checkout: '/checkout',
  paymentCode: '/payment-code',

  enterprise: {
    info: '/enterprise/info',
    refund: '/enterprise/refund',
    dashboard: '/enterprise/dashboard',
    products: '/enterprise/product',
    order: '/enterprise/order',
    revenue: '/enterprise/revenue',
    wallet: '/enterprise/wallet',
    editProduct: '/enterprise/edit-product',
    addProduct: '/enterprise/add-product',
    createOrderWithoutProduct: '/order-without-product',
  },

  priceChart: '/price-chart',
  support: '/support',
  supportDetail: '/support-detail',
  supportRequest: '/support-request',
  exchange: '/exchange',

  //
  connect: '/connect',
};
