import { UserState } from './user.interface';
import {
  UserRole,
  UserType,
  UserStatus,
  KycType,
  KycStatus,
} from '../../models/user';
import { AddressType } from '../../models/address';

export const userInitialState: UserState = {
  isFetching: false,
  _id: null,
  info: {
    display_name: '',
    first_name: '',
    last_name: '',
    role: UserRole.User,
    type: UserType.Customer,
    status: UserStatus.Pending,

    _id: '',
    username: '',
    email: '',
    phone: '',
    sponsor: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    security_version: 1,
    address: '',
    country: '',
    country_code: '',
    country_phone: '',
    country_name: '',
    kyc_status: KycStatus.None,
  },
  access_token: null,
  two_fa: {
    isFetching: false,
    two_fa_uri: null,
    token: '',
    tokenError: null,
  },
  form: {
    isFetching: false,
    first_name: '',
    first_nameError: null,
    last_name: '',
    last_nameError: null,
    display_name: '',
    display_nameError: null,
    phone: '',
    phoneError: null,
    business_name: '',
    business_nameError: null,
    address: '',
    addressError: null,
    apartment: '',
    apartmentError: null,
    city: '',
    cityError: null,
    country: '',
    countryError: null,
    country_code: '',
    country_codeError: null,
    postal_code: '',
    postal_codeError: null,
    password: '',
    passwordError: null,
    new_password: '',
    new_passwordError: null,
    confirm_password: '',
    confirm_passwordError: null,

    kyc_fullName: '',
    kyc_fullNameError: null,
    kyc_birthday: new Date('2000-01-01'),
    kyc_birthdayError: null,
    kyc_address: '',
    kyc_addressError: null,
    kyc_type: KycType.Passport,
    kyc_number: '',
    kyc_numberError: null,
    kyc_provided_date: new Date('2000-01-01'),
    kyc_provided_dateError: null,
    kyc_provided_area: '',
    kyc_provided_areaError: null,
    kyc_front_image: '',
    kyc_front_imageError: null,
    kyc_back_image: '',
    kyc_back_imageError: null,
    kyc_selfie_image: '',
    kyc_selfie_imageError: null,

    enterprise_name: '',
    enterprise_nameError: null,
    enterprise_logo: '',
    enterprise_logoError: null,
    enterprise_address: '',
    enterprise_addressError: null,
  },
  address: {
    data: [],
    form: {
      address: '',
      apartment: '',
      city: '',
      country: '',
      postal_code: '',
      country_code: '',
      type: AddressType.Billing,
      addressError: null,
      apartmentError: null,
      cityError: null,
      countryError: null,
      postal_codeError: null,
      country_codeError: null,
      typeError: null,
    },
  },
  myChildren: {
    isGot: false,
    data: [],
  },
  connected: false,
  key: '',
  walletAddress: '',
  balance: 0,
  bandwidth: 0,
  bandwidthUsed: 0,
  energy: 0,
  energyUsed: 0,
  frozenBalance: 0,
  reward: 0,
  asset: [],
  drc10Token: [],
  drc20Token: [],
};
